const CASE_OPTIONS = ['SNAKE', 'KEBAB', 'UPPER', 'CAMEL', 'PASCAL'];
const CORRECT_REQUEST_MESSAGE = '"/<TEXT_TO_CONVERT>?toCase=<CASE_NAME>".';
const CORRECT_REQUEST = 'Correct request is: ';

module.exports = {
  CASE_OPTIONS,
  CORRECT_REQUEST_MESSAGE,
  CORRECT_REQUEST,
};
