const CASE_OPTIONS = ['SNAKE', 'KEBAB', 'UPPER', 'CAMEL', 'PASCAL'];
const CORRECT_REQUEST_MESSAGE = '"/<TEXT_TO_CONVERT>?toCase=<CASE_NAME>".';

module.exports = {
  CASE_OPTIONS, CORRECT_REQUEST_MESSAGE,
};
